<?php

namespace MLequer\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-16 at 21:41:19.
 */
class SetupCommandTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SetupCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SetupCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MLequer\Command\SetupCommand::setRootDir
     * @todo   Implement testSetRootDir().
     */
    public function testSetRootDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
